name: nanahoshi-v2

services:
  postgres:
    image: postgres
    container_name: nanahoshi-v2-postgres
    environment:
      POSTGRES_DB: nanahoshi-v2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - nanahoshi-v2_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  nanahoshi-v2_postgres_data:
